import { SignedIn, SignedOut, SignInButton, SignUpButton } from '@clerk/nextjs';
import DashboardNavBar from './components/DashboardNavBar';
import { Toaster } from 'react-hot-toast';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

export default function DashboardLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="bg-white font-pop">
        <Toaster />
        <SignedOut>
          <SignInButton />
          <SignUpButton />
        </SignedOut>
        <SignedIn>
          <DashboardNavBar />
          {children}
        </SignedIn>
      </body>
    </html>
  );
}
